<?php
/** @var Zend\View\Model\ViewModel $this */
/** @var NightsWatch\Entity\User $identity */
/** @var NightsWatch\Form\EventForm $form */

if (!$form->get('preview')->getValue()) {
    echo $this->bootstrapForm($form, 'horizontal');
} else {
    $tempEvent = new \NightsWatch\Entity\Event();
    $tempEvent->start = new DateTime();
    $tempEvent->user = $identity;
    $tempEvent->name = $form->get('name')->getValue();
    $tempEvent->description = $form->get('description')->getValue();
    $form->get('name')->setAttribute('type', 'hidden');
    $form->get('description')->setAttribute('type', 'hidden');
    echo $this->partial('nights-watch/announcement/partials/event', ['event' => $tempEvent, 'useEventLink' => false]);
    echo $this->bootstrapForm($form, 'horizontal');
}
