<form action="download" method="get" class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="keephat">Keep my hat</label>
        <div class="controls">
            <input type="hidden" name="keephat" value="0" />
            <input type="checkbox" name="keephat" id="keephat" value="1" />
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input name="submit" class="btn btn-primary" value="Generate Skin" type="submit"/>
        </div>
    </div>
</form>
