<?php
/** @var \NightsWatch\Entity\Announcement $announcement */
use Carbon\Carbon;
use \NightsWatch\Entity\User;

if (!isset($useArticleLink)) {
    $useArticleLink = true;
}
$date = Carbon::instance($announcement->timestamp);
$postUrl = $this->url('id', ['controller' => 'announcement', 'action' => 'view', 'id' => $announcement->id]);
?>
<article class="announcement">
    <header>
        <h2>
            <img alt="" src="<?= $announcement->user->getAvatar(32) ?>" class="announcement-avatar"/>
            <?= $useArticleLink ? "<a href=\"{$postUrl}\">" : null ?>
                <?= htmlspecialchars($announcement->title); ?>
            <?= $useArticleLink ? '</a>' : null ?>
        </h2>
    </header>
    <?php if ($announcement->lowestReadableRank > User::RANK_CIVILIAN): ?>
        <p class="alert alert-error">This post is classified.  The contents are privileged information, only available to members of rank <?= User::getRankName($announcement->lowestReadableRank); ?> and up. <a href="#" class="close" data-dismiss="alert">&times;</a></p>
    <?php endif; ?>
    <div class="well well-small">
        <?= $announcement->getParsedContent(); ?>
    </div>
    <footer>
        posted <time pubdate datetime="<?= $date->format(Carbon::ISO8601); ?>"><?= $date->diffForHumans() ?></time>
        by <a rel="author"><?= htmlspecialchars($announcement->user->getTitleWithName()) ?></a>
    </footer>
</article>
