<h2>Rules of Engagement</h2>
<div class="well">
    <p>We, the Night's Watch, self-declared protectors of the realm - have
        seen chaos ensue the land, with public servers increasingly growing
        towards brave survivors killing each other on sight. We seek an end to
        this growing ruthless hostility, and have thus compiled a list of
        aggressive actions. Taking any of the listed actions below will warrant
        the immediate and merciless destruction of your life.</p>

    <p>Abiding by these rules does not mean that you must enforce them. If a
        person you deeply trust does any of the below, adhering to these rules
        in no way means that you need attack them. These rules are simply
        guidelines in order to best establish when it is okay to stop being
        friendly and attack in order to save your own life.</p>

    <p>As stated above, taking any of the below actions will be counted as
        aggression:</p>

    <ul>
        <li>Running directly towards a player</li>
        <li>Offensively attacking a player</li>
        <li>Approaching a player within a 15 block radius</li>
        <li>Approaching a player with your sword out.

            <ul>
                <li>As the common signal of peace is to put your swords in defensive
                    motion, it is advised that after you are sure a player has seen you
                    do so, to swap out to a non-harming item such as water or (even
                    better) shears. Additionally, in order to protect your own life, you
                    should not approach the player while his or her sword is still
                    drawn.
                </li>
            </ul>
        </li>
        <li>Following a player (especially off the road)</li>
        <li>Drawing back a bow for any length of time towards a player</li>
    </ul>

    <p>Taking any of these actions will be viewed as aggression and your
        life may be forfeit.</p>

    <blockquote>
        <em>Signed and Decreed,</em><br/> <img
            src="http://i.imgur.com/Hrr9I.png"/><br/> <em>Navarr, First Lord Commander and Founder
            of The Night's Watch</em>
    </blockquote>
</div>

<h2>Rules of the Watch</h2>
<div class="well">
    <ol>
        <li>You may not kill any player unprovoked. Read the rules of
            engagement (which you are bound to) to understand what we consider "provocation"
        </li>
        <li>You may not steal from players - If you commit to a trade you must
            follow through with it.
        </li>
        <li>You may not share information on our website with non-Night's
            Watch players - For announcements, only link them. If they can't see
            them, then they're not supposed to.
        </li>
        <li>You may not be in a MineZ guild or clan other than The Night's Watch.
        </li>
        <li>You may not post inappropriate (NSFW/NSFL) content in the chatrooms or mumble.
        </li>
        <li>You may not leave the watch without a request to do so signed by
            the Lord Commander
        </li>
    </ol>
    <p>
        Doing any of the above may warrant your immediate placement as a
        deserter. Particularly heinous offenses may lead to members of the
        Watch hunting you down. The Watch is supposed to be a great big happy
        family. And you know what they say - <q><strong><em>You do not anger
                    the family.</em> </strong> </q>
    </p>
</div>
