<?php
/** @var Zend\View\Model\ViewModel $this */
/** @var NightsWatch\Form\VerifyForm $form */
/** @var array $errors */
?>
<?php if ($done): ?>
    <div class="alert alert-success">
        <p>Your password has been changed successfully. We've also gone ahead and automatically logged you in.</p>
    </div>
    <?php return; endif; ?>
<h2>Password Reset</h2><br />
<?php if (count($errors)): ?>
    <div class="alert alert-error">
        <?php foreach ($errors as $error): ?>
            <p><?= $error ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?= $this->bootstrapForm($form, 'horizontal'); ?>
