<?php
/** @var \NightsWatch\Entity\Event $event */
/** @var \NightsWatch\Entity\User $user */
use \NightsWatch\Entity\User;
use \NightsWatch\Entity\EventRsvp as RSVP;

if (!isset($useEventLink)) {
    $useEventLink = true;
}
if (!isset($showRsvp)) {
    $showRsvp = false;
}
if (!isset($showRegion)) {
    $showRegion = false;
}
if (!isset($showType)) {
    $showType = false;
}
$eventUrl = $this->url('id', ['controller' => 'event', 'action' => 'view', 'id' => $event->id]);
$iso8601  = $event->start->format(DateTime::ISO8601);

// Generate the RSVP groups

$rsvpGroups = [
    RSVP::RSVP_ATTENDING => [],
    RSVP::RSVP_MAYBE     => [],
    RSVP::RSVP_ABSENT    => [],
];

$usersAttendance = RSVP::RSVP_ABSENT;

// This is for the Sharknado.
// SHARKNADO ALWAYS RSVP's ATTENDING
foreach ($event->rsvps as $rsvp) {
    $rsvpGroups[$rsvp->attendance][] = $rsvp->user;
    if (!is_null($user) && $rsvp->user->username == $user->username) {
        $usersAttendance = $rsvp->attendance;
    }
}

?>
<article class="event span9 offset1">
    <header>
        <time class="time sidetime" datetime="<?= $iso8601; ?>" title="<?= $iso8601 ?>">
            <span class="dateformat" data-format="H:i" data-unix="<?= $event->start->getTimestamp(); ?>">
                <?= $event->start->format('H:i T'); ?>
            </span>
            <span class="date dateformat" data-format="M j" data-unix="<?= $event->start->getTimestamp(); ?>">
                <?= $event->start->format('M j'); ?>
            </span>
        </time>
        <h2>
            <?= $useEventLink ? "<a href=\"{$eventUrl}\">" : null ?>
            <?= htmlspecialchars($event->name); ?>
            <?= $useEventLink ? '</a>' : null ?>
        </h2>
        <time class="time visible-phone hidden-tablet" datetime="<?= $iso8601 ?>" title="<?= $iso8601 ?>">
            <span class="dateformat" data-format="F j, Y" data-unix="<?= $event->start->getTimestamp(); ?>">
                <?= $event->start->format('F j, Y'); ?>
            </span>
            at
            <span class="date dateformat" data-format="H:i" data-unix="<?= $event->start->getTimestamp(); ?>">
                <?= $event->start->format('H:i T'); ?>
            </span>
            <br /><br />
        </time>
    </header>
    <?php if ($event->lowestViewableRank > User::RANK_CIVILIAN): ?>
        <p class="alert alert-error fade in">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            This event is classified. All information concerning it is classified and only available to members of
            rank <?= User::getRankName($event->lowestViewableRank); ?> and up.
        </p>
    <?php endif; ?>
    <div class="well well-small">
        <?= $event->getParsedDescription(); ?>
    </div>
    <footer>
        posted by <a rel="author"><?= htmlspecialchars($event->user->getTitleWithName()) ?></a>
        <?php if (!$showRsvp && $event->start->getTimestamp() > time()): ?>
            <br/>
            <em>
                <?php
                $attendingString = count($rsvpGroups[RSVP::RSVP_ATTENDING]) + 1;
                $maybe           = count($rsvpGroups[RSVP::RSVP_MAYBE]);
                if ($maybe > 0) {
                    $attendingString .= " to " . ($attendingString + $maybe);
                }
                ?>
                <?= $attendingString; ?> attending
                &middot;
                <a href="<?= $eventUrl ?>">RSVP</a>
            </em>
        <?php endif; ?>
        <?php if ($event->canEdit($user)): ?>
            &middot;
            <a href="<?= $this->url('id', ['controller' => 'event', 'action' => 'edit', 'id' => $event->id]); ?>">
                edit
            </a>
        <?php endif; ?>
    </footer>
    <?php if ($showRegion && $event->region): ?>
        <hr/>
        <aside>
            <h3>Region</h3>

            <div class="well well-small"><?= $event->getRegionName(); ?></div>
        </aside>
    <?php endif; ?>
    <?php if ($showType && $event->type): ?>
        <hr/>
        <aside>
            <h3>Event Type</h3>

            <div class="well well-small"><?= $event->getTypeName(); ?></div>
        </aside>
    <?php endif; ?>
    <?php if (!is_null($user) && $showRsvp && $event->start->getTimestamp() > time()): ?>
        <hr/>
        <aside>
            <h3>Attendance</h3>
            <?php
            if (is_null($event->leader) || $user->id != $event->leader->id) {
                $form = new \NightsWatch\Form\RsvpForm($event);
                $form->setAttribute('action', $this->url('home', ['controller' => 'event', 'action' => 'rsvp']));
                $form->get('attendance')->setValue($usersAttendance);
                echo $this->bootstrapForm($form);
            }
            ?>
            <?php if (!is_null($event->leader)): ?>
                <h4>Lead By</h4>
                <div class="well well-small">
                    <table class="user-table">
                        <?= $this->partial('nights-watch/user/partials/listDescription', ['user' => $event->leader]); ?>
                    </table>
                </div>
            <?php endif; ?>
            <?php if ($showRsvp): ?>
                <?php foreach ($rsvpGroups as $rsvpType => $rsvpGroup): ?>
                    <h4><?= RSVP::getRsvpNameFromType($rsvpType); ?> <span
                            class="badge badge-info"><?= count($rsvpGroup); ?></span></h4>
                    <div class="well well-small">
                        <?php foreach ($rsvpGroup as $user): ?>
                            <?= $this->partial('partials/listHead', ['user' => $user]); ?>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </aside>
    <?php endif; ?>
</article>
