<?php
/** @var int $month */
/** @var int $year */
$days = cal_days_in_month(CAL_GREGORIAN, $month, $year);
$date = \DateTime::createFromFormat('Y n j', "{$year} {$month} 1");
$today = new \DateTime();
$oneDay = new \DateInterval('P1D');
// Back up to a Sunday
while ($date->format('w') > 0) {
    $date->sub($oneDay);
}
?>
<div id="calendar-container">
<div class="well well-small" id="calendar-well">
    <table>
        <thead>
        <tr>
            <th colspan="7">
                <h2><?= DateTime::createFromFormat('Y-n', "{$year}-{$month}")->format('F Y'); ?></h2>
            </th>
        </tr>
        <tr>
            <th>Sunday</th>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
            <th>Saturday</th>
        </tr>
        </thead>
        <tbody>
        <?php while ($date->format('n') < $month + 1 || $date->format('w') != 0): ?>
            <?php if ($date->format('w') == 0): ?><tr><?php endif; ?>
            <td class="<?= $date->format('n') != $month ? 'othermonth ' : null ?><?= $date->format('Y-m-d') == $today->format('Y-m-d') ? 'today ' : null ?>">
                <div class="date"><?= $date->format('j'); ?></div>
            </td>
            <?php if ($date->format('w') == 6): ?></tr><?php endif; ?>
            <?php $date->add($oneDay); ?>
        <?php endwhile; ?>
        </tbody>
    </table>
</div>
</div>
<style>
    table {
        border: 1px solid #666;
        border-collapse: collapse;
    }

    td, th {
        border: 1px solid #666;
        padding: 5px;
        text-align: center;
    }

    td {
        width: 90px;
        height: 90px;
        position: relative;
    }

    td.othermonth {
        opacity: 0.5;
    }
    td.today .date {
        color: #45caff;
    }

    td .date {
        position: absolute;
        top: 0;
        right: 0;
        border-style: solid;
        border-color: #666;
        border-width: 0 0 1px 1px;
        width: 25px;
        height: 25px;
        line-height: 25px;
    }
    #calendar-container {
        text-align: center;
    }
    #calendar-well {
        display: inline-block;
        text-align: left;
    }
</style>
