<?php
/** @var NightsWatch\Entity\User $user */
$ranks = $this->ranks;
?>
<div class="well" style="font-style:italic;">
    <p>Where they came from, and why they were here no longer mattered to us. We didn't
        know.. and those who had known didn't remember. They didn't <strong>want</strong> to remember. It was
        terrifying. It was traumatic... but all that mattered was that we were here now. Fighting each and every
        day to stay alive among the countless hordes. </p>

    <p>People were divided.. fighting for supplies.. trying their hardest to survive, no matter who got caught in their
        backlash. We wanted to be different. Life wasn't something to be so casually thrown away. It should be honored.
        Saved. We weren't going to divide ourselves. We weren't going to cut each others' throats. We were going to
        survive.. and we were going to do it together.</p>

    <p>And most importantly.. we were going to eradicate the Undead.</p>

    <p>The Leader gathered us together. Appointed us ranks. Took us under his wings and tried to make sure we had ample
        supplies. And then, after he was sure we could survive - he made us take an oath - to swear loyalty to the realm
        we lived in, and all those that would inhabit it. And so, we took the words &mdash;</p>

    <br/>

    <div style="font-style:italic;" class="well well-large">
        <p>Hear my words and bear witness to my vow:</p>
    <p>Night gathers, and now my watch begins. It shall not end until my
        banishment. I shall take no mate, hold no lands, render no children. I shall wear no crowns and win no glory. I
        shall live and die at my post. I am the sword in the darkness. I am the watcher on the walls. I am the fire that
        burns against the cold, the light that brings the dawn, the horn that wakes the sleepers, the shield that guards
        the realms of men. I pledge my life and honor to the Night's Watch, for this night and all the nights to
        come.</p>
    </div>

    <div class="text-center">
        <p>Will you take our words, and join us in our fight?</p>
        <p>Take the first step by logging in - this doesn't register you into our ranks, but lets you chat with our members.</p>

        <p class="text-center"><a href="/join"><img src="/img/sign_in_with_shotbow_btn.png" alt="Sign in with Shotbow" /></a></p>
    </div>
</div>
