<?php
/** @var Zend\View\Model\ViewModel $this */
/** @var NightsWatch\Form\RegisterForm $form */
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<div class="control-group">
    <label for="register-email" class="control-label">Email</label>
    <div class="controls">
        <?= $this->formEmail($form->get('email')); ?>
    </div>
</div>
    <div class="control-group">
        <label for="register-username" class="control-label">Username</label>
        <div class="controls">
            <?= $this->formInput($form->get('username')); ?>
            <span class="help-block">This must be exactly the same as your Minecraft character's username.</span>
        </div>
    </div>
    <div class="control-group">
        <label for="register-password" class="control-label">Password</label>
        <div class="controls">
            <?= $this->formPassword($form->get('password')); ?>
            <span class="help-block">Please create a secure password for your new account.</span>
            <br />
            <?= $this->formPassword($form->get('password2')); ?>
            <span class="help-block">Please verify your new password by typing it again.</span>
        </div>
    </div>
    <div class="control-group">
        <?php $form->get('submit')->setAttribute('class', 'btn btn-primary'); ?>
        <div class="controls">
            <?= $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
<?= $this->form()->closeTag($form); ?>
