<?php

/** @var string $mod */

?>
<h2 id="mod-about">About</h2>
<div class="well">
    <p>The official Night's Watch mod displays a cape depicting the rank of all Night's Watch members and recruits,
        allowing them to easily be identified as friendlies.</p>
</div>
<p class="alert alert-danger fade in">The content on this page is CLASSIFIED! Never give a person the direct link
    to The Night's Watch mod, nor the raw file. Always, <strong>always</strong>, send them to this link to get it for
    themselves. Violation of this order may result in your permanent removal from The Night's Watch.</p>
<h2>Downloading &amp; Installing</h2>
<h3 id="install-forge">Installing Minecraft Forge for 1.7.2</h3>
<div class="well">
    <p>If you have previously installed Minecraft Force for 1.7.2, you may <a href="#install-mod">install the mod</a>.
    </p>

    <h4 id="install-minecraft">Installing Minecraft 1.7.2</h4>

    <p>Right now, the Night's Watch Mod only works for Minecraft 1.7.2. If you already played Minecraft 1.7.2 on your
        current computer, you can skip to <a href="#install-forge">Installing Forge</a></p>

    <p>Steps:</p>
    <ol>
        <li>Open the Minecraft Launcher (<a href="http://i.imgur.com/PT42ePq.png">Example of Launcher</a>)</li>
        <li>Click the "New Profile" button and create a profile for 1.7.2. You may call it anything you want, but you
            <a href="http://i.imgur.com/w7ZdAqP.png">must specify 1.7.2 as the version to use</a>. Leave the other
            settings as their defaults, and click the <strong>Save Profile</strong> button. Under the Welcome message
            on the bottom right hand side, it should say "Ready to play Minecraft 1.7.2".
        </li>
        <li>Click the Play button, and wait for Minecraft (the game) to finish launching. It may take a few moments for
            it to download and install Minecraft 1.7.2
        </li>
        <li>Congratulations. You may now <a href="#install-forge">Install Forge</a>.</li>
    </ol>

    <h4 id="install-forge">Installing Forge for Minecraft 1.7.2</h4>

    <p>Steps:</p>
    <ol>
        <li>Download the <a href="http://j.mp/1oJh9ei">Minecraft Forge Installer</a></li>
        <li>Run the file you downloaded. You should get a <a href="http://i.imgur.com/knNyMKN.png">Mod System installer
                window.</a>
            <ol>
                <li>On Windows, you should be able to double click it to open it. If this opens a folder view instead
                    of showing you a window, you'll need to right click the file and select "Open With." At that point,
                    navigate to your Java installation directory (something like C:\Program Files\Java\ or
                    C:\Program Files (x86)\Java) and select the jre folder with the highest number (hopefully jre7).
                    Once in that folder, select the "bin" directory, and then select the file "javaw.exe" as the program
                    to open the file with. (<a href="http://i.imgur.com/tAxbrdz.png">Example</a>)
                </li>
            </ol>
        </li>
        <li>Select "Install Client" and click "OK." A progress window should popup, and when it is complete you should
            get a <a href="http://i.imgur.com/Nphfe0F.png">"Complete" window</a>.
        </li>
    </ol>
</div>
<h3 id="install-mod">Installing The Night's Watch Mod</h3>
<div class="well">
    <ol>
        <li>Download <a href="/other/<?= $mod ?>">The Night's Watch mod</a>.</li>
        <li>Visit your .minecraft directory. On Windows, this looks like
            <strong>C:\users\&lt;username&gt;\AppData\Roaming\.minecraft\</strong>. Once there, if a
            <strong>mods</strong> folder does not already exist, create one. In this folder, paste the file you
            downloaded in Step 1.
        </li>
        <li>Open the Minecraft launcher.</li>
        <li><a href="http://i.imgur.com/3FiFZog.png">Select your Forge profile</a>. If you followed this page's
            instructions for installing Forge, it should just be named "Forge."
        </li>
        <li>Click the great big ol' <strong>Play</strong> button.</li>
        <li>If you have installed everything successfully, you should have a <a href="http://i.imgur.com/NWVdCZl.png">
                mods button</a>, and upon clicking it should see <a href="http://i.imgur.com/tDNLqzG.png">Night's
                Watch Capes</a> or something similar in it's list. If so: Congratulations, you now have the mod! If
            not, feel free to seek help in the #recruit or higher chat rooms.
        </li>
    </ol>
</div>
