<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('The Night\'s Watch'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('theme-color', '#000000');
    ?>

    <!-- Le styles -->
    <?php
    echo $this
        ->headLink(
            [
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ]
        )
        ->headLink(
            [
                'rel' => 'manifest',
                'href' => $this->basePath() . '/manifest.json'
            ]
        )
        ->headLink(
            [
                'rel' => 'icon',
                'href' => $this->basePath() . '/img/logo.png'
            ]
        )
        ->appendStylesheet($this->basePath() . '/css/before-bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
        ->appendStylesheet($this->basePath() . '/css/datepicker.css')
        ->appendStylesheet($this->basePath() . '/css/darkstrap.min.css')
        ->appendStylesheet($this->basePath() . '/css/after-bootstrap.css?v=20140511')
    ?>

    <!-- Scripts -->
    <?php
    echo $this->headScript()
        ->prependFile($this->basePath() . '/js/global.js')
        ->prependFile($this->basePath() . '/js/date.js')
        ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?= $this->url('home') ?>"><?= $this->translate('The Night\'s Watch') ?></a>

            <div class="nav-collapse collapse">
                <?= $this->bootstrapNavbar('navigation'); ?>
                <?=
                $this->hasIdentity ? $this->bootstrapNavbar('right-auth-navigation')->setUlClass(
                    'nav pull-right'
                ) : $this->bootstrapNavbar('right-noauth-navigation')->setUlClass('nav pull-right'); ?>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div class="container">
    <?php echo $this->content; ?>
    <?php if ($this->hasIdentity): ?>
    <div class="classified" style="position:fixed;top:0;left:0;right:0;bottom:0;font-size:172pt;opacity:0.007;font-family:serif;z-index:-1;pointer-events:none;text-align:center;line-height:100%;margin-top:-81pt;margin-left:-215px;">
        <?= $this->identity->name ?><br /><?= $this->identity->name ?><br /><?= $this->identity->name ?><br /><?= $this->identity->name ?>
    </div>
    <?php endif; ?>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-2330128-19', 'minez-nightswatch.com');
<?php if ($this->hasIdentity): ?>
    ga('set', '&uid', '<?= $this->identity->id ?>');
<?php endif; ?>
    ga('send', 'pageview');
</script>
</body>
</html>
