<div class="row-fluid">
    <div class="span10">
        <div class="well well-small better-scrollbar" id="chat-message-container">
            <div id="chat-messages">
                <ol>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                    <li><span class="faux-invisible">[</span><span class="timestamp">20:33</span><span
                            class="faux-invisible">] </span><span class="faux-invisible">&lt;</span><a
                            href="">Navarr</a><span class="faux-invisible">&gt; </span>Some random message here.
                    </li>
                </ol>
            </div>
        </div>
        <form id="chat-message" class="row-fluid">
            <div class="span10">
                <input type="text" class="span12"/>
            </div>
            <div class="span2">
                <input type="submit" class="btn btn-inverse span12" value="Post"/>
            </div>
        </form>
    </div>
    <div class="span2 hidden-phone hidden-print">
        <div class="well well-small better-scrollbar" id="chat-viewers">
            <ol>
                <li><a href=""><img src="//minotar.net/helm/Navarr/16.png"/> Navarr</a></li>
                <li><a href=""><img src="//minotar.net/helm/sssdl4/16.png"/> sssdl4</a></li>
            </ol>
        </div>
    </div>
</div>

